### ISSUE TITLE
Bug: Approved tech removed on project update

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/StackPortfolio#78]
### Describe the Bug

When you add a new tech to a project, the tech is automatically marked as not approved. In the admin, if I then mark a tech as approved, it shows up correctly on the frontend. However, if I then go into the **_same_** project and try to update it, there is a 500 error and the tech is deleted from the database. 

This does not happen if:
1. The tech is already approved
2. You add the newly approved tech in another project first

### Steps to Reproduce

1. Add a tech not on the list of provided tech to a project 
2. In the admin, mark the tech as approved
3. Go to the same project and update any details

### Attach Screenshots or Logs

![Image](https://github.com/stephendawsondev/StackPortfolio/assets/57060620/e1fe7e8d-d59c-4f55-9d18-5d5d138d0703)

![Image](https://github.com/stephendawsondev/StackPortfolio/assets/57060620/8ec31254-abf5-41ab-b2ab-c5c726c75127)

![Image](https://github.com/stephendawsondev/StackPortfolio/assets/57060620/7c5c7d33-3d60-4c40-ba1b-0e54b2988675)

![Image](https://github.com/stephendawsondev/StackPortfolio/assets/57060620/e9a1a41f-ce52-4aeb-9ba6-691aada30ab5)

![Image](https://github.com/stephendawsondev/StackPortfolio/assets/57060620/71c49db2-06ad-4b41-a195-5df3da95ba16)

Logs:
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/user/default_username/project/project-test-6/edit

Django Version: 3.2.22
Python Version: 3.9.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cloudinary_storage',
 'django.contrib.staticfiles',
 'cloudinary',
 'widget_tweaks',
 'custom_account',
 'project',
 'technology']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'allauth.account.middleware.AccountMiddleware']



Traceback (most recent call last):
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()

The above exception (FOREIGN KEY constraint failed) was the direct cause of the following exception:
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/stephendawson/Documents/StackPortfolio/project/views.py", line 122, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/views/generic/edit.py", line 194, in post
    return super().post(request, *args, **kwargs)
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/Users/stephendawson/Documents/StackPortfolio/project/views.py", line 159, in form_valid
    project.technologies.add(tech_id)
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/db/models/fields/related_descriptors.py", line 957, in add
    self._add_items(
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/db/transaction.py", line 246, in __exit__
    connection.commit()
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/db/backends/base/base.py", line 266, in commit
    self._commit()
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/stephendawson/Library/Python/3.9/lib/python/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()

Exception Type: IntegrityError at /user/default_username/project/project-test-6/edit
Exception Value: FOREIGN KEY constraint failed
```

### Additional Informatiom

I believe the issue is that the reference to the record is changed once it is approved.

Next step could be to investigate SQL logs - I found this article on enabling SQL logging: https://www.yellowduck.be/posts/enabling-sql-logging-in-django

**Comment by stephendawsondev** [comment]
I inadvertently resolved this bug during sprint 3 when trying to address why  even some already approved tech was being removed - it seems the issue also stemmed from the fact I was removing tech if it didn't exist on another project, which seemed to make sense at the time but does not make sense to do now.
